apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 982851e637d65771a95597c72592fea54fdaf4c2
    app.openshift.io/vcs-uri: https://github.com/thomasirmer/eurobridge-app
  labels:
    app.kubernetes.io/instance: eurobridge-app
    app.kubernetes.io/name: eurobridge-app
  name: eurobridge-app
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: eurobridge-app
    app.kubernetes.io/name: eurobridge-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 982851e637d65771a95597c72592fea54fdaf4c2
    app.openshift.io/vcs-uri: https://github.com/thomasirmer/eurobridge-app
  labels:
    app.kubernetes.io/instance: eurobridge-app
    app.kubernetes.io/name: eurobridge-app
  name: eurobridge-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: eurobridge-app
      app.kubernetes.io/name: eurobridge-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 982851e637d65771a95597c72592fea54fdaf4c2
        app.openshift.io/vcs-uri: https://github.com/thomasirmer/eurobridge-app
      labels:
        app.kubernetes.io/instance: eurobridge-app
        app.kubernetes.io/name: eurobridge-app
    spec:
      containers:
      - image: quay.io/thomasirmer/eurobridge-app:982851e637d65771a95597c72592fea54fdaf4c2
        name: eurobridge-app
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 982851e637d65771a95597c72592fea54fdaf4c2
    app.openshift.io/vcs-uri: https://github.com/thomasirmer/eurobridge-app
  labels:
    app.kubernetes.io/instance: eurobridge-app
    app.kubernetes.io/name: eurobridge-app
  name: eurobridge-app
spec:
  to:
    kind: Service
    name: eurobridge-app
